export const techKeywords = [
  'Full Stack',
  'Web Developer',
  'Frontend',
  'Backend',
  'Software Engineer',
  'Developer',
  'Programmer',
  'Engineer',
  'React',
  'Node',
  'JavaScript',
  'TypeScript',
  'Tech',
  'Technology',
  'IT',
  'App Developer',
  'Mobile Developer',
  'Data Scientist',
  'Machine Learning',
  'Cloud',
  'DevOps',
]; 